/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseTextField: typeof import('./src/components/base/BaseTextField.vue')['default']
    HomeClients: typeof import('./src/components/home/HomeClients.vue')['default']
    HomeProjects: typeof import('./src/components/home/HomeProjects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
